In [6]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [12]:
FILE_1 = pd.read_csv(r'C:\Users\alfim\Desktop\prova\prova.csv')
FILE_1

,Titolo,Directed by,Distributed by,Running time,Country,Budget,Box office
0,Wings,William A. Wellman,Paramount Famous Lasky Corporation,"Original release:, , 111 minutes, [2], , Resto...",United States,"$2 million, [4]","$3.8 million (U.S. and Canada rentals), [5]"
1,7th Heaven,Frank Borzage,Fox Film Corporation,110 min,United States,"$1.3 million, [1]","$2.5 million, [2]"
2,The Racket,Lewis Milestone,Paramount Pictures,84 minutes,United States,NaN,NaN
3,The Broadway Melody,Harry Beaumont,Metro-Goldwyn-Mayer,100 minutes,United States,"$379,000, [3]","$4.4 million, [3]"
4,Alibi,Roland West,United Artists,90 minutes,United States,NaN,NaN
...,...,...,...,...,...,...,...
4493,The Boy and the Heron,Hayao Miyazaki,Toho,124 minutes,Japan,NaN,"US$167.5 million, [1], [2]"
4494,Elemental,Peter Sohn,Walt Disney Studios Motion Pictures,"101 minutes, [1]",United States,"$200 million, [2]","$496.4 million, [3], [4]"
4495,Nimona,Nick BrunoTroy Quane,Netflix,"99 minutes, [1]",United States,NaN,NaN
4496,Robot Dreams,Pablo Berger,".mw-parser-output .plainlist ol,.mw-parser-out...",102 minutes,NaN,"€5 million, [3]","$717,064, [4]"
4497,Spider-Man: Across the Spider-Verse,".mw-parser-output .plainlist ol,.mw-parser-out...",Sony Pictures Releasing,"140 minutes, [1]",United States,"$100–150 million, [2], [3]","$690.9, , million, [4], [5]"

In [16]:
FILE_1.Budget = FILE_1.Budget.str.split('[')
FILE_1.Budget = FILE_1.Budget.str.get(0)
FILE_1.Budget

0             $2 million,
1           $1.3 million,
2                      NaN
3               $379,000,
4                      NaN
               ...
4493                   NaN
4494        $200 million,
4495                   NaN
4496          €5 million,
4497    $100–150 million,
Name: Budget, Length: 4498, dtype: object

In [20]:
FILE_1['Box office'] = FILE_1['Box office'].str.split('[')
FILE_1['Box office'] = FILE_1['Box office'].str.get(0)
FILE_1['Box office']

0       $3.8 million (U.S. and Canada rentals),
1                                 $2.5 million,
2                                            NaN
3                                 $4.4 million,
4                                            NaN
                          ...
4493                          US$167.5 million,
4494                            $496.4 million,
4495                                         NaN
4496                                  $717,064,
4497                        $690.9,  , million,
Name: Box office, Length: 4498, dtype: object

In [22]:
FILE_1['Distributed by'] = FILE_1['Distributed by'].str.split('[')
FILE_1['Distributed by'] = FILE_1['Distributed by'].str.get(0)
FILE_1['Distributed by']

0                      Paramount Famous Lasky Corporation
1                                    Fox Film Corporation
2                                      Paramount Pictures
3                                     Metro-Goldwyn-Mayer
4                                          United Artists
                              ...
4493                                                 Toho
4494                  Walt Disney Studios Motion Pictures
4495                                              Netflix
4496    .mw-parser-output .plainlist ol,.mw-parser-out...
4497                              Sony Pictures Releasing
Name: Distributed by, Length: 4498, dtype: object

In [24]:
FILE_1['Running time'] = FILE_1['Running time'].str.split('[')
FILE_1['Running time'] = FILE_1['Running time'].str.get(0)
FILE_1['Running time']

0       Original release:, , 111 minutes,
1                                  110 min
2                               84 minutes
3                              100 minutes
4                               90 minutes
                       ...
4493                           124 minutes
4494                         101 minutes,
4495                          99 minutes,
4496                           102 minutes
4497                         140 minutes,
Name: Running time, Length: 4498, dtype: object

In [29]:
FILE_1.Country = FILE_1.Country.str.split('[')
FILE_1.Country = FILE_1.Country.str.get(0)
FILE_1.Country

0       United States
1       United States
2       United States
3       United States
4       United States
            ...
4493            Japan
4494    United States
4495    United States
4496              NaN
4497    United States
Name: Country, Length: 4498, dtype: object

In [31]:
FILE_1.to_csv('Prova movies pulito.csv' , index = None)

In [33]:
FILE_1 = pd.read_csv(r'C:\Users\alfim\Desktop\prova\prova.csv')
FILE_1

,Titolo,Directed by,Distributed by,Running time,Country,Budget,Box office
0,Wings,William A. Wellman,Paramount Famous Lasky Corporation,"Original release:, , 111 minutes,",United States,2000000,38000000 (US and Canada rentals)
1,7th Heaven,Frank Borzage,Fox Film Corporation,110 min,United States,13000000,25000000
2,The Racket,Lewis Milestone,Paramount Pictures,84 minutes,United States,NaN,NaN
3,The Broadway Melody,Harry Beaumont,Metro-Goldwyn-Mayer,100 minutes,United States,379000,44000000
4,Alibi,Roland West,United Artists,90 minutes,United States,NaN,NaN
...,...,...,...,...,...,...,...
4493,The Boy and the Heron,Hayao Miyazaki,Toho,124 minutes,Japan,NaN,US1675000000
4494,Elemental,Peter Sohn,Walt Disney Studios Motion Pictures,"101 minutes,",United States,200000000,4964000000
4495,Nimona,Nick BrunoTroy Quane,Netflix,"99 minutes,",United States,NaN,NaN
4496,Robot Dreams,Pablo Berger,".mw-parser-output .plainlist ol,.mw-parser-out...",102 minutes,NaN,€5000000,717064
4497,Spider-Man: Across the Spider-Verse,".mw-parser-output .plainlist ol,.mw-parser-out...",Sony Pictures Releasing,"140 minutes,",United States,100–150 million,6909 000000

In [35]:
FILE_1['Directed by'] = FILE_1['Directed by'].str.split('[')
FILE_1['Directed by'] = FILE_1['Directed by'].str.get(0)
FILE_1['Directed by']

0                                      William A. Wellman
1                                           Frank Borzage
2                                         Lewis Milestone
3                                          Harry Beaumont
4                                             Roland West
                              ...
4493                                       Hayao Miyazaki
4494                                           Peter Sohn
4495                                 Nick BrunoTroy Quane
4496                                         Pablo Berger
4497    .mw-parser-output .plainlist ol,.mw-parser-out...
Name: Directed by, Length: 4498, dtype: object

In [37]:
FILE_1['Running time'] = FILE_1['Running time'].str.split('minutes')
FILE_1['Running time'] = FILE_1['Running time'].str.get(0)
FILE_1['Running time']

0       Original release:, , 111
1                         110 min
2                             84
3                            100
4                             90
                  ...
4493                         124
4494                         101
4495                          99
4496                         102
4497                         140
Name: Running time, Length: 4498, dtype: object

In [39]:
FILE_1.Budget = FILE_1.Budget.str.split('(')
FILE_1.Budget = FILE_1.Budget.str.get(0)
FILE_1.Budget

0               2000000
1              13000000
2                    NaN
3                379000
4                    NaN
              ...
4493                 NaN
4494          200000000
4495                 NaN
4496           €5000000
4497    100–150 million
Name: Budget, Length: 4498, dtype: object

In [41]:
FILE_1['Box office'] = FILE_1['Box office'].str.split('(')
FILE_1['Box office'] = FILE_1['Box office'].str.get(0)
FILE_1['Box office']

0           38000000
1           25000000
2                 NaN
3           44000000
4                 NaN
            ...
4493    US1675000000
4494      4964000000
4495              NaN
4496          717064
4497    6909  000000
Name: Box office, Length: 4498, dtype: object

In [43]:
FILE_1.to_csv('Prova movies pulito.csv' , index = None)

In [45]:
FILE_1 = pd.read_csv(r'C:\Users\alfim\Desktop\prova\movies-pulito.csv')
FILE_1

,Titolo,Directed by,Distributed by,Running time,Country,Budget,Box office
0,Wings,William A. Wellman,Paramount Famous Lasky Corporation,111,United States,2000000,38000000
1,7th Heaven,Frank Borzage,Fox Film Corporation,110,United States,13000000,25000000
2,The Broadway Melody,Harry Beaumont,Metro-Goldwyn-Mayer,100,United States,379000,44000000
3,Hollywood Revue,Charles Reisner,Metro-Goldwyn-Mayer,130,United States,426000,2421000
4,All Quiet on the Western Front,Lewis Milestone,Universal Pictures,152,United States,12000000,3000000
...,...,...,...,...,...,...,...
1679,Raya and the Last Dragon,".mw-parser-output .plainlist ol,.mw-parser-out...",Walt Disney StudiosMotion Pictures,107,United States,100 000000,1304 000000
1680,Puss in Boots: The Last Wish,Joel Crawford,Universal Pictures,102,United States,90–110000000,4852000000
1681,Turning Red,Domee Shi,Walt Disney StudiosMotion Pictures,100,United States,175000000,215000000
1682,Elemental,Peter Sohn,Walt Disney Studios Motion Pictures,101,United States,200000000,4964000000
1683,Spider-Man: Across the Spider-Verse,".mw-parser-output .plainlist ol,.mw-parser-out...",Sony Pictures Releasing,140,United States,100–150000000,6909 000000

In [47]:
FILE_1['Box office'] = FILE_1['Box office'].str.split('-')
FILE_1['Box office'] = FILE_1['Box office'].str.get(1)
FILE_1['Box office']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1679   NaN
1680   NaN
1681   NaN
1682   NaN
1683   NaN
Name: Box office, Length: 1684, dtype: float64

In [49]:
FILE_1.Budget = FILE_1.Budget.str.split('-')
FILE_1.Budget = FILE_1.Budget.str.get(1)
FILE_1.Budget

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1679    NaN
1680    NaN
1681    NaN
1682    NaN
1683    NaN
Name: Budget, Length: 1684, dtype: object

In [51]:
FILE_1['Running time'] = FILE_1['Running time'].str.split('or')
FILE_1['Running time'] = FILE_1['Running time'].str.get(1)
FILE_1['Running time']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1679    NaN
1680    NaN
1681    NaN
1682    NaN
1683    NaN
Name: Running time, Length: 1684, dtype: object

In [53]:
FILE_1['Running time'] = FILE_1['Running time'].str.split('-')
FILE_1['Running time'] = FILE_1['Running time'].str.get(1)
FILE_1['Running time']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1679   NaN
1680   NaN
1681   NaN
1682   NaN
1683   NaN
Name: Running time, Length: 1684, dtype: float64

In [55]:
FILE_1['Running time'] = FILE_1['Running time'].str.split(' ')
FILE_1['Running time'] = FILE_1['Running time'].str.get(1)
FILE_1['Running time']

AttributeError: Can only use .str accessor with string values!

In [ ]:
FILE_1['Running time'] = FILE_1['Running time'].str.split('/')
FILE_1['Running time'] = FILE_1['Running time'].str.get(1)
FILE_1['Running time']

In [ ]:
FILE_1.to_csv('Prova movies pulito.csv' , index = None)